name: InfiniChest
main: com.pantherman594.infinichest.Main
description: Infinitely large storage chest. By PantherMan594. (c) PantherMan594.
author: PantherMan594
version: #VERSION#
commands:
  chest:
    description: An infinite chest!
    usage: /chest <sub command> <args>